export const ADD_BOARD = 'ADD_BOARD';
export const EDIT_TITLE_BOARD = 'EDIT_TITLE_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const ADD_CHILD_BOARD = 'ADD_CHILD_BOARD';
export const DELETE_CHILD_BOARD = 'DELETE_CHILD_BOARD';
