export const ADD_CARD = 'ADD_CARD';
export const EDIT_TITLE_CARD = 'EDIT_TITLE_CARD';
export const EDIT_DESCRIPTION_CARD = 'EDIT_DESCRIPTION_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const ADD_TASK_CARD = 'ADD_TASK_CARD';
export const DELETE_TASK_CARD = 'DELETE_TASK_CARD';
export const ADD_COMMENT_CARD = 'ADD_COMMENT_CARD';
export const DELETE_COMMENT_CARD = 'DELETE_COMMENT_CARD';
