export const ADD_COLUMN = 'ADD_COLUMN';
export const EDIT_TITLE_COLUMN = 'EDIT_TITLE_COLUMN';
export const DELETE_COLUMN = 'DELETE_COLUMN';
export const ADD_CHILD_COLUMN = 'ADD_CHILD_COLUMN';
export const DELETE_CHILD_COLUMN = 'DELETE_CHILD_COLUMN';
